In [16]:
import pandas as pd

In [17]:
import json
with open('strapi-admin-panel.basic_analyses.json') as outf:
    df=json.load(outf)

In [18]:
df1=pd.DataFrame.from_dict(df)
df1.head()

,_id,testId,userId,isBonusAttempted,sections,subjects,totalTimeTaken,totalMarkScored,totalAttempted,totalCorrect,accuracy,submittedAt,__v
0,{'$oid': '626ab9ea24905064ba37bd34'},{'$oid': '6242de22af9dd6d0f5e0aee7'},{'$oid': '625e645cefa6f45a6d242f41'},False,"[{'_id': {'$oid': '626ab9ea24905064ba37bd35'},...","[{'_id': {'$oid': '626ab9ea24905064ba37bd75'},...",78,5.0,10,4,40.000000,{'$date': '2022-04-28T15:59:38.654Z'},0
1,{'$oid': '626f8759783460b593e5e7d0'},{'$oid': '6242de22af9dd6d0f5e0aee9'},{'$oid': '60767d3fa86f753846145692'},False,"[{'_id': {'$oid': '626f8759783460b593e5e7d1'},...","[{'_id': {'$oid': '626f8759783460b593e5e814'},...",303,-0.5,13,2,15.384615,{'$date': '2022-05-02T07:25:13.257Z'},0
2,{'$oid': '626f87f8783460b593e5e8d0'},{'$oid': '6242de22af9dd6d0f5e0aee7'},{'$oid': '60767d3fa86f753846145692'},False,"[{'_id': {'$oid': '626f87f8783460b593e5e8d1'},...","[{'_id': {'$oid': '626f87f8783460b593e5e918'},...",112,-3.5,17,2,11.764706,{'$date': '2022-05-02T07:27:52.973Z'},0
3,{'$oid': '626f9b43d1872602514e4618'},{'$oid': '61923f2ad42d105914c0ee67'},{'$oid': '60c859a597812656fc783f13'},False,"[{'_id': {'$oid': '626f9b43d1872602514e4619'},...","[{'_id': {'$oid': '626f9b43d1872602514e467a'},...",1,4.0,1,1,100.000000,{'$date': '2022-05-02T08:50:11.853Z'},0
4,{'$oid': '6270fd16ab73fe1ec7acc623'},{'$oid': '614dd5dda0282649c036e79f'},{'$oid': '60767d3fa86f753846145692'},False,"[{'_id': {'$oid': '6270fd16ab73fe1ec7acc624'},...","[{'_id': {'$oid': '6270fd16ab73fe1ec7acc68e'},...",463,5.0,10,3,30.000000,{'$date': '2022-05-03T09:59:50.860Z'},0

In [19]:
df1.shape

(156, 13)

In [20]:
df1['_id1']=df1['_id'].apply(lambda x:x.get('$oid'))
df1.head()

,_id,testId,userId,isBonusAttempted,sections,subjects,totalTimeTaken,totalMarkScored,totalAttempted,totalCorrect,accuracy,submittedAt,__v,_id1
0,{'$oid': '626ab9ea24905064ba37bd34'},{'$oid': '6242de22af9dd6d0f5e0aee7'},{'$oid': '625e645cefa6f45a6d242f41'},False,"[{'_id': {'$oid': '626ab9ea24905064ba37bd35'},...","[{'_id': {'$oid': '626ab9ea24905064ba37bd75'},...",78,5.0,10,4,40.000000,{'$date': '2022-04-28T15:59:38.654Z'},0,626ab9ea24905064ba37bd34
1,{'$oid': '626f8759783460b593e5e7d0'},{'$oid': '6242de22af9dd6d0f5e0aee9'},{'$oid': '60767d3fa86f753846145692'},False,"[{'_id': {'$oid': '626f8759783460b593e5e7d1'},...","[{'_id': {'$oid': '626f8759783460b593e5e814'},...",303,-0.5,13,2,15.384615,{'$date': '2022-05-02T07:25:13.257Z'},0,626f8759783460b593e5e7d0
2,{'$oid': '626f87f8783460b593e5e8d0'},{'$oid': '6242de22af9dd6d0f5e0aee7'},{'$oid': '60767d3fa86f753846145692'},False,"[{'_id': {'$oid': '626f87f8783460b593e5e8d1'},...","[{'_id': {'$oid': '626f87f8783460b593e5e918'},...",112,-3.5,17,2,11.764706,{'$date': '2022-05-02T07:27:52.973Z'},0,626f87f8783460b593e5e8d0
3,{'$oid': '626f9b43d1872602514e4618'},{'$oid': '61923f2ad42d105914c0ee67'},{'$oid': '60c859a597812656fc783f13'},False,"[{'_id': {'$oid': '626f9b43d1872602514e4619'},...","[{'_id': {'$oid': '626f9b43d1872602514e467a'},...",1,4.0,1,1,100.000000,{'$date': '2022-05-02T08:50:11.853Z'},0,626f9b43d1872602514e4618
4,{'$oid': '6270fd16ab73fe1ec7acc623'},{'$oid': '614dd5dda0282649c036e79f'},{'$oid': '60767d3fa86f753846145692'},False,"[{'_id': {'$oid': '6270fd16ab73fe1ec7acc624'},...","[{'_id': {'$oid': '6270fd16ab73fe1ec7acc68e'},...",463,5.0,10,3,30.000000,{'$date': '2022-05-03T09:59:50.860Z'},0,6270fd16ab73fe1ec7acc623

In [21]:
df1['testid1']=df1['testId'].apply(lambda x:x.get('$oid'))
df1.head()

,_id,testId,userId,isBonusAttempted,sections,subjects,totalTimeTaken,totalMarkScored,totalAttempted,totalCorrect,accuracy,submittedAt,__v,_id1,testid1
0,{'$oid': '626ab9ea24905064ba37bd34'},{'$oid': '6242de22af9dd6d0f5e0aee7'},{'$oid': '625e645cefa6f45a6d242f41'},False,"[{'_id': {'$oid': '626ab9ea24905064ba37bd35'},...","[{'_id': {'$oid': '626ab9ea24905064ba37bd75'},...",78,5.0,10,4,40.000000,{'$date': '2022-04-28T15:59:38.654Z'},0,626ab9ea24905064ba37bd34,6242de22af9dd6d0f5e0aee7
1,{'$oid': '626f8759783460b593e5e7d0'},{'$oid': '6242de22af9dd6d0f5e0aee9'},{'$oid': '60767d3fa86f753846145692'},False,"[{'_id': {'$oid': '626f8759783460b593e5e7d1'},...","[{'_id': {'$oid': '626f8759783460b593e5e814'},...",303,-0.5,13,2,15.384615,{'$date': '2022-05-02T07:25:13.257Z'},0,626f8759783460b593e5e7d0,6242de22af9dd6d0f5e0aee9
2,{'$oid': '626f87f8783460b593e5e8d0'},{'$oid': '6242de22af9dd6d0f5e0aee7'},{'$oid': '60767d3fa86f753846145692'},False,"[{'_id': {'$oid': '626f87f8783460b593e5e8d1'},...","[{'_id': {'$oid': '626f87f8783460b593e5e918'},...",112,-3.5,17,2,11.764706,{'$date': '2022-05-02T07:27:52.973Z'},0,626f87f8783460b593e5e8d0,6242de22af9dd6d0f5e0aee7
3,{'$oid': '626f9b43d1872602514e4618'},{'$oid': '61923f2ad42d105914c0ee67'},{'$oid': '60c859a597812656fc783f13'},False,"[{'_id': {'$oid': '626f9b43d1872602514e4619'},...","[{'_id': {'$oid': '626f9b43d1872602514e467a'},...",1,4.0,1,1,100.000000,{'$date': '2022-05-02T08:50:11.853Z'},0,626f9b43d1872602514e4618,61923f2ad42d105914c0ee67
4,{'$oid': '6270fd16ab73fe1ec7acc623'},{'$oid': '614dd5dda0282649c036e79f'},{'$oid': '60767d3fa86f753846145692'},False,"[{'_id': {'$oid': '6270fd16ab73fe1ec7acc624'},...","[{'_id': {'$oid': '6270fd16ab73fe1ec7acc68e'},...",463,5.0,10,3,30.000000,{'$date': '2022-05-03T09:59:50.860Z'},0,6270fd16ab73fe1ec7acc623,614dd5dda0282649c036e79f

In [22]:
df1['userid1']=df1['userId'].apply(lambda x:x.get('$oid'))
df1.head()

,_id,testId,userId,isBonusAttempted,sections,subjects,totalTimeTaken,totalMarkScored,totalAttempted,totalCorrect,accuracy,submittedAt,__v,_id1,testid1,userid1
0,{'$oid': '626ab9ea24905064ba37bd34'},{'$oid': '6242de22af9dd6d0f5e0aee7'},{'$oid': '625e645cefa6f45a6d242f41'},False,"[{'_id': {'$oid': '626ab9ea24905064ba37bd35'},...","[{'_id': {'$oid': '626ab9ea24905064ba37bd75'},...",78,5.0,10,4,40.000000,{'$date': '2022-04-28T15:59:38.654Z'},0,626ab9ea24905064ba37bd34,6242de22af9dd6d0f5e0aee7,625e645cefa6f45a6d242f41
1,{'$oid': '626f8759783460b593e5e7d0'},{'$oid': '6242de22af9dd6d0f5e0aee9'},{'$oid': '60767d3fa86f753846145692'},False,"[{'_id': {'$oid': '626f8759783460b593e5e7d1'},...","[{'_id': {'$oid': '626f8759783460b593e5e814'},...",303,-0.5,13,2,15.384615,{'$date': '2022-05-02T07:25:13.257Z'},0,626f8759783460b593e5e7d0,6242de22af9dd6d0f5e0aee9,60767d3fa86f753846145692
2,{'$oid': '626f87f8783460b593e5e8d0'},{'$oid': '6242de22af9dd6d0f5e0aee7'},{'$oid': '60767d3fa86f753846145692'},False,"[{'_id': {'$oid': '626f87f8783460b593e5e8d1'},...","[{'_id': {'$oid': '626f87f8783460b593e5e918'},...",112,-3.5,17,2,11.764706,{'$date': '2022-05-02T07:27:52.973Z'},0,626f87f8783460b593e5e8d0,6242de22af9dd6d0f5e0aee7,60767d3fa86f753846145692
3,{'$oid': '626f9b43d1872602514e4618'},{'$oid': '61923f2ad42d105914c0ee67'},{'$oid': '60c859a597812656fc783f13'},False,"[{'_id': {'$oid': '626f9b43d1872602514e4619'},...","[{'_id': {'$oid': '626f9b43d1872602514e467a'},...",1,4.0,1,1,100.000000,{'$date': '2022-05-02T08:50:11.853Z'},0,626f9b43d1872602514e4618,61923f2ad42d105914c0ee67,60c859a597812656fc783f13
4,{'$oid': '6270fd16ab73fe1ec7acc623'},{'$oid': '614dd5dda0282649c036e79f'},{'$oid': '60767d3fa86f753846145692'},False,"[{'_id': {'$oid': '6270fd16ab73fe1ec7acc624'},...","[{'_id': {'$oid': '6270fd16ab73fe1ec7acc68e'},...",463,5.0,10,3,30.000000,{'$date': '2022-05-03T09:59:50.860Z'},0,6270fd16ab73fe1ec7acc623,614dd5dda0282649c036e79f,60767d3fa86f753846145692

In [23]:
df1.drop(['_id','userId','testId'],axis=1,inplace=True)
df1.head()

,isBonusAttempted,sections,subjects,totalTimeTaken,totalMarkScored,totalAttempted,totalCorrect,accuracy,submittedAt,__v,_id1,testid1,userid1
0,False,"[{'_id': {'$oid': '626ab9ea24905064ba37bd35'},...","[{'_id': {'$oid': '626ab9ea24905064ba37bd75'},...",78,5.0,10,4,40.000000,{'$date': '2022-04-28T15:59:38.654Z'},0,626ab9ea24905064ba37bd34,6242de22af9dd6d0f5e0aee7,625e645cefa6f45a6d242f41
1,False,"[{'_id': {'$oid': '626f8759783460b593e5e7d1'},...","[{'_id': {'$oid': '626f8759783460b593e5e814'},...",303,-0.5,13,2,15.384615,{'$date': '2022-05-02T07:25:13.257Z'},0,626f8759783460b593e5e7d0,6242de22af9dd6d0f5e0aee9,60767d3fa86f753846145692
2,False,"[{'_id': {'$oid': '626f87f8783460b593e5e8d1'},...","[{'_id': {'$oid': '626f87f8783460b593e5e918'},...",112,-3.5,17,2,11.764706,{'$date': '2022-05-02T07:27:52.973Z'},0,626f87f8783460b593e5e8d0,6242de22af9dd6d0f5e0aee7,60767d3fa86f753846145692
3,False,"[{'_id': {'$oid': '626f9b43d1872602514e4619'},...","[{'_id': {'$oid': '626f9b43d1872602514e467a'},...",1,4.0,1,1,100.000000,{'$date': '2022-05-02T08:50:11.853Z'},0,626f9b43d1872602514e4618,61923f2ad42d105914c0ee67,60c859a597812656fc783f13
4,False,"[{'_id': {'$oid': '6270fd16ab73fe1ec7acc624'},...","[{'_id': {'$oid': '6270fd16ab73fe1ec7acc68e'},...",463,5.0,10,3,30.000000,{'$date': '2022-05-03T09:59:50.860Z'},0,6270fd16ab73fe1ec7acc623,614dd5dda0282649c036e79f,60767d3fa86f753846145692

In [24]:
df1['userid1'].nunique()

23

In [25]:
df1['testid1'].nunique()

107

In [26]:
a=df1['userid1'].drop_duplicates()

In [32]:
df1.shape

(156, 12)

In [27]:
a

0      625e645cefa6f45a6d242f41
1      60767d3fa86f753846145692
3      60c859a597812656fc783f13
8      639b0819dd54ec28a1a32c7c
9      621e507604540e207ea790e1
47     6299e0341eaa0318fc98370e
65     61a63a836eae089191c6a71a
77     60e2b39e566129478143c10c
78     6336a211d650b0115cc1efaa
79     6336d2d9d650b0115cc1f2d4
80     6336d3dcd650b0115cc1f421
81     62319d3d599b7f5f5ad80da4
89     637efcb5986f5b98e56ae309
92     637c66d9a1931b2464a2f9cc
93     637366741d2350364f069a41
95     641ab7f84e6d46b1d397f3b3
96     641b51fd4e6d46b1d397f864
97     641b591b4e6d46b1d397f9f9
98     637249eb0bff3e0fa490c01a
101    664dec71ad0879bdb974a83a
104    66504499ad0879bdb974d6a0
105    66503de1ad0879bdb974d5d8
119    6651b837ad0879bdb9756b2d
Name: userid1, dtype: object

In [28]:
df1['testid1'].nunique()

107

In [29]:
df1['isBonusAttempted'].nunique()

1

In [30]:
df1.drop('isBonusAttempted',axis=1,inplace=True)
df1.head()

,sections,subjects,totalTimeTaken,totalMarkScored,totalAttempted,totalCorrect,accuracy,submittedAt,__v,_id1,testid1,userid1
0,"[{'_id': {'$oid': '626ab9ea24905064ba37bd35'},...","[{'_id': {'$oid': '626ab9ea24905064ba37bd75'},...",78,5.0,10,4,40.000000,{'$date': '2022-04-28T15:59:38.654Z'},0,626ab9ea24905064ba37bd34,6242de22af9dd6d0f5e0aee7,625e645cefa6f45a6d242f41
1,"[{'_id': {'$oid': '626f8759783460b593e5e7d1'},...","[{'_id': {'$oid': '626f8759783460b593e5e814'},...",303,-0.5,13,2,15.384615,{'$date': '2022-05-02T07:25:13.257Z'},0,626f8759783460b593e5e7d0,6242de22af9dd6d0f5e0aee9,60767d3fa86f753846145692
2,"[{'_id': {'$oid': '626f87f8783460b593e5e8d1'},...","[{'_id': {'$oid': '626f87f8783460b593e5e918'},...",112,-3.5,17,2,11.764706,{'$date': '2022-05-02T07:27:52.973Z'},0,626f87f8783460b593e5e8d0,6242de22af9dd6d0f5e0aee7,60767d3fa86f753846145692
3,"[{'_id': {'$oid': '626f9b43d1872602514e4619'},...","[{'_id': {'$oid': '626f9b43d1872602514e467a'},...",1,4.0,1,1,100.000000,{'$date': '2022-05-02T08:50:11.853Z'},0,626f9b43d1872602514e4618,61923f2ad42d105914c0ee67,60c859a597812656fc783f13
4,"[{'_id': {'$oid': '6270fd16ab73fe1ec7acc624'},...","[{'_id': {'$oid': '6270fd16ab73fe1ec7acc68e'},...",463,5.0,10,3,30.000000,{'$date': '2022-05-03T09:59:50.860Z'},0,6270fd16ab73fe1ec7acc623,614dd5dda0282649c036e79f,60767d3fa86f753846145692

In [31]:
df1['sections'][0]

[{'_id': {'$oid': '626ab9ea24905064ba37bd35'},
  'sectionId': {'$oid': '626a8f31901c260c2e4bd53a'},
  'questions': [{'_id': {'$oid': '626ab9ea24905064ba37bd36'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd4d8'},
    'markedOptions': [],
    'inputValue': {'value': '0', 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': 120,
    'status': 'notAnswered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd37'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd4dd'},
    'markedOptions': [],
    'inputValue': {'value': '0', 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': 120,
    'status': 'notAnswered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd38'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd4e2'},
    'markedOptions': [],
    'inputValue': {'value': '0', 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': 120,
    'status': 'notAnswered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd39'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd4e7'},
    'markedOptions': [],
    'inputValue': {'value': '0', 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': 120,
    'status': 'notAnswered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd3a'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd4ec'},
    'markedOptions': [],
    'inputValue': {'value': '0', 'isCorrect': False},
    'timeTaken': 2,
    'timeLeftWhenAttempted': 120,
    'status': 'notAnswered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd3b'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd4f1'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd3c'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd4f6'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd3d'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd4fb'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd3e'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd500'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd3f'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd505'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd40'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd50a'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd41'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd50f'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd42'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd514'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd43'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd519'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd44'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd51e'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd45'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd523'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd46'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd528'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd47'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd52d'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd48'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd532'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'}],
  'analysis': {'totalTimeTaken': 2,
   'totalMarkScored': 0,
   'totalAttempted': 0,
   'totalCorrect': 0,
   'accuracy': 0}},
 {'_id': {'$oid': '626ab9ea24905064ba37bd49'},
  'sectionId': {'$oid': '626a8f32901c260c2e4bd5c5'},
  'questions': [{'_id': {'$oid': '626ab9ea24905064ba37bd4a'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd58b'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd4b'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd590'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd4c'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd595'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd4d'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd59a'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd4e'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd59f'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd4f'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd5a4'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd50'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd5a9'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd51'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd5ae'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd52'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd5b3'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd53'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd5b8'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd54'},
    'questionId': {'$oid': '626a8f31901c260c2e4bd5bd'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'}],
  'analysis': {'totalTimeTaken': 0,
   'totalMarkScored': 0,
   'totalAttempted': 0,
   'totalCorrect': 0,
   'accuracy': 0}},
 {'_id': {'$oid': '626ab9ea24905064ba37bd55'},
  'sectionId': {'$oid': '626a8f32901c260c2e4bd64e'},
  'questions': [{'_id': {'$oid': '626ab9ea24905064ba37bd56'},
    'questionId': {'$oid': '626a8f32901c260c2e4bd614'},
    'markedOptions': [],
    'inputValue': {'value': '0', 'isCorrect': False},
    'timeTaken': 1,
    'timeLeftWhenAttempted': 120,
    'status': 'notAnswered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd57'},
    'questionId': {'$oid': '626a8f32901c260c2e4bd619'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd58'},
    'questionId': {'$oid': '626a8f32901c260c2e4bd61e'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd59'},
    'questionId': {'$oid': '626a8f32901c260c2e4bd623'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd5a'},
    'questionId': {'$oid': '626a8f32901c260c2e4bd628'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd5b'},
    'questionId': {'$oid': '626a8f32901c260c2e4bd62d'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd5c'},
    'questionId': {'$oid': '626a8f32901c260c2e4bd632'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd5d'},
    'questionId': {'$oid': '626a8f32901c260c2e4bd637'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd5e'},
    'questionId': {'$oid': '626a8f32901c260c2e4bd63c'},
    'markedOptions': [],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': None,
    'status': 'notVisited'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd5f'},
    'questionId': {'$oid': '626a8f32901c260c2e4bd641'},
    'markedOptions': [],
    'inputValue': {'value': '0', 'isCorrect': False},
    'timeTaken': 0,
    'timeLeftWhenAttempted': 120,
    'status': 'notAnswered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd60'},
    'questionId': {'$oid': '626a8f32901c260c2e4bd646'},
    'markedOptions': [{'_id': {'$oid': '626ab9ea24905064ba37bd61'},
      'optionId': '1ce750',
      'isCorrect': True}],
    'inputValue': {'isCorrect': False},
    'timeTaken': 3,
    'timeLeftWhenAttempted': 120,
    'status': 'answered'}],
  'analysis': {'totalTimeTaken': 4,
   'totalMarkScored': 2,
   'totalAttempted': 1,
   'totalCorrect': 1,
   'accuracy': 100}},
 {'_id': {'$oid': '626ab9ea24905064ba37bd62'},
  'sectionId': {'$oid': '626a8f33901c260c2e4bd6da'},
  'questions': [{'_id': {'$oid': '626ab9ea24905064ba37bd63'},
    'questionId': {'$oid': '626a8f33901c260c2e4bd68f'},
    'markedOptions': [{'_id': {'$oid': '626ab9ea24905064ba37bd64'},
      'optionId': '75a31e',
      'isCorrect': True}],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 8,
    'timeLeftWhenAttempted': 120,
    'status': 'answered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd65'},
    'questionId': {'$oid': '626a8f33901c260c2e4bd697'},
    'markedOptions': [{'_id': {'$oid': '626ab9ea24905064ba37bd66'},
      'optionId': '96ec27',
      'isCorrect': True}],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 8,
    'timeLeftWhenAttempted': 120,
    'status': 'answered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd67'},
    'questionId': {'$oid': '626a8f33901c260c2e4bd69f'},
    'markedOptions': [{'_id': {'$oid': '626ab9ea24905064ba37bd68'},
      'optionId': '95a7eb',
      'isCorrect': False}],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 8,
    'timeLeftWhenAttempted': 120,
    'status': 'answered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd69'},
    'questionId': {'$oid': '626a8f33901c260c2e4bd6a7'},
    'markedOptions': [{'_id': {'$oid': '626ab9ea24905064ba37bd6a'},
      'optionId': '731be9',
      'isCorrect': False}],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 8,
    'timeLeftWhenAttempted': 120,
    'status': 'answered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd6b'},
    'questionId': {'$oid': '626a8f33901c260c2e4bd6af'},
    'markedOptions': [{'_id': {'$oid': '626ab9ea24905064ba37bd6c'},
      'optionId': 'dff04c',
      'isCorrect': False}],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 8,
    'timeLeftWhenAttempted': 120,
    'status': 'answered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd6d'},
    'questionId': {'$oid': '626a8f33901c260c2e4bd6b7'},
    'markedOptions': [{'_id': {'$oid': '626ab9ea24905064ba37bd6e'},
      'optionId': '7ab7bd',
      'isCorrect': False}],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 8,
    'timeLeftWhenAttempted': 119,
    'status': 'answered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd6f'},
    'questionId': {'$oid': '626a8f33901c260c2e4bd6bf'},
    'markedOptions': [{'_id': {'$oid': '626ab9ea24905064ba37bd70'},
      'optionId': '7e3c9f',
      'isCorrect': True}],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 8,
    'timeLeftWhenAttempted': 119,
    'status': 'answered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd71'},
    'questionId': {'$oid': '626a8f33901c260c2e4bd6c7'},
    'markedOptions': [{'_id': {'$oid': '626ab9ea24905064ba37bd72'},
      'optionId': '0503df',
      'isCorrect': False}],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 8,
    'timeLeftWhenAttempted': 119,
    'status': 'answered'},
   {'_id': {'$oid': '626ab9ea24905064ba37bd73'},
    'questionId': {'$oid': '626a8f33901c260c2e4bd6cf'},
    'markedOptions': [{'_id': {'$oid': '626ab9ea24905064ba37bd74'},
      'optionId': '113d17',
      'isCorrect': False}],
    'inputValue': {'value': None, 'isCorrect': False},
    'timeTaken': 8,
    'timeLeftWhenAttempted': 119,
    'status': 'answered'}],
  'analysis': {'totalTimeTaken': 72,
   'totalMarkScored': 3,
   'totalAttempted': 9,
   'totalCorrect': 3,
   'accuracy': 33.33333333333333}}]